window.MRLD_TRANSLATIONS = window.MRLD_TRANSLATIONS || {};
window.MRLD_TRANSLATIONS["fr-CA"] = {
  "meta": {
    "locale": "fr-CA",
    "language": "Français (Canada)",
    "direction": "ltr",
    "source": "English HTML",
    "notes": "Canadian French localization. Edit this file only for French copy; layout and design remain shared."
  },
  "global": {
    "MRLD | Industrial Equipment. Global Supply.": "MRLD | Équipement industriel. Approvisionnement mondial.",
    "MRLD connects selected industrial equipment manufacturers with qualified buyers across Canada and international markets.": "MRLD met en relation des fabricants sélectionnés d’équipement industriel avec des acheteurs qualifiés au Canada et sur les marchés internationaux.",
    "Equipment": "Équipement",
    "Project Logistics": "Logistique de projet",
    "Industries": "Secteurs",
    "About": "À propos",
    "Contact": "Contact",
    "Sectors": "Secteurs",
    "Explore": "Explorer",
    "Company": "Entreprise",
    "Connect": "Nous joindre",
    "Email": "Courriel",
    "Privacy": "Confidentialité",
    "Privacy Policy": "Politique de confidentialité",
    "Terms": "Conditions",
    "Terms of Use": "Conditions d’utilisation",
    "Legal": "Mentions légales",
    "LinkedIn": "LinkedIn",
    "MRLD Home": "Accueil MRLD",
    "Open navigation": "Ouvrir la navigation",
    "Close navigation": "Fermer la navigation",
    "Language selector": "Sélecteur de langue",
    "Manufacturers": "Fabricants",
    "Buyers": "Acheteurs",
    "Partner with MRLD": "Collaborer avec MRLD",
    "Source Equipment": "Trouver de l’équipement",
    "Power Generation": "Production d’énergie",
    "Construction Machinery": "Machinerie de construction",
    "LET'S CONNECT": "PRENONS CONTACT",
    "Let's build the connection.": "Créons le lien.",
    "Industrial equipment. Global supply. Market access.": "Équipement industriel. Approvisionnement mondial. Accès aux marchés.",
    "Connecting selected manufacturers with qualified buyers across Canada and international markets.": "Mettre en relation des fabricants sélectionnés avec des acheteurs qualifiés au Canada et sur les marchés internationaux.",
    "Connecting selected manufacturers with qualified buyers across established and emerging markets.": "Mettre en relation des fabricants sélectionnés avec des acheteurs qualifiés sur des marchés établis et émergents.",
    "🇨🇦 Canadian company. Global reach.": "🇨🇦 Entreprise canadienne. Portée mondiale.",
    "© 2026 MRLD, a Sayudi Inc. company. All rights reserved.": "© 2026 MRLD, une entreprise de Sayudi Inc. Tous droits réservés.",
    "© 2026 MRLD, a Sayudi Inc. company.": "© 2026 MRLD, une entreprise de Sayudi Inc.",
    "Contact MRLD": "Communiquer avec MRLD",
    "Founder & Director": "Fondateur et directeur",
    "· Montreal, Quebec, Canada": "· Montréal, Québec, Canada",
    "Canada": "Canada",
    "Asia": "Asie",
    "International Markets": "Marchés internationaux",
    "Construction": "Construction",
    "Mining": "Mines",
    "Energy": "Énergie",
    "Manufacturing": "Fabrication",
    "Infrastructure": "Infrastructure",
    "Material Handling": "Manutention",
    "Other": "Autre",
    "Effective date:": "Date d’entrée en vigueur :",
    "August 24, 2026": "24 août 2026",
    "QUESTIONS?": "DES QUESTIONS ?",
    "Name": "Nom",
    "MRLD Privacy Policy": "Politique de confidentialité de MRLD",
    "The most recent version will be published on this page.": "La version la plus récente sera publiée sur cette page.",
    "MRLD / Sayudi Inc.": "MRLD / Sayudi Inc.",
    "Ali Saïd | MRLD": "Ali Saïd | MRLD"
  },
  "pages": {
    "home": {
      "INDUSTRIAL EQUIPMENT · CANADA": "ÉQUIPEMENT INDUSTRIEL · CANADA",
      "ASIA": "ASIE",
      "Connecting manufacturers with buyers.": "Relier les fabricants aux acheteurs.",
      "MRLD connects selected industrial equipment manufacturers across Asia with qualified buyers in Canada.": "MRLD met en relation des fabricants sélectionnés d’équipement industriel en Asie avec des acheteurs qualifiés au Canada.",
      "MRLD connects manufacturers and buyers": "MRLD relie les fabricants aux acheteurs",
      "FOR MANUFACTURERS": "POUR LES FABRICANTS",
      "Looking to enter new markets?": "Vous visez de nouveaux marchés ?",
      "MRLD provides market representation, business development, and access to qualified buyers for selected industrial equipment manufacturers seeking opportunities in Canada.": "MRLD offre de la représentation commerciale, du développement des affaires et un accès à des acheteurs qualifiés pour des fabricants sélectionnés d’équipement industriel qui cherchent des occasions au Canada.",
      "FOR BUYERS": "POUR LES ACHETEURS",
      "Looking for another source?": "Vous cherchez une autre source d’approvisionnement ?",
      "MRLD helps organizations identify and acquire industrial equipment from selected manufacturers across Asia through a Canadian commercial point of contact.": "MRLD aide les organisations à repérer et à acquérir de l’équipement industriel auprès de fabricants sélectionnés en Asie, par l’entremise d’un point de contact commercial canadien.",
      "SELECTED EQUIPMENT": "ÉQUIPEMENT SÉLECTIONNÉ",
      "Industrial equipment for demanding environments.": "De l’équipement industriel pour des environnements exigeants.",
      "MRLD works across equipment categories where supplier access, reliability, and execution matter.": "MRLD intervient dans des catégories d’équipement où l’accès aux fournisseurs, la fiabilité et la capacité d’exécution comptent.",
      "Diesel generators, gas engines, and power generation equipment.": "Génératrices diesel, moteurs au gaz et équipement de production d’énergie.",
      "Explore →": "Explorer →",
      "Equipment for construction, infrastructure, and earthmoving applications.": "Équipement destiné à la construction, aux infrastructures et aux travaux de terrassement.",
      "Beyond these categories": "Au-delà de ces catégories",
      "Industrial equipment manufacturers exploring the Canadian market are invited to start a conversation.": "Les fabricants d’équipement industriel qui explorent le marché canadien sont invités à engager la conversation.",
      "Discuss your equipment →": "Présentez-nous votre équipement →"
    },
    "equipment": {
      "Industrial Equipment | MRLD": "Équipement industriel | MRLD",
      "MRLD sources industrial equipment around application, specifications, operating conditions, support, lead time, and commercial fit.": "MRLD recherche de l’équipement industriel en fonction de l’application, des spécifications, des conditions d’exploitation, du soutien, des délais et de l’adéquation commerciale.",
      "BEFORE YOU SOURCE": "AVANT DE VOUS APPROVISIONNER",
      "The wrong equipment may look right on paper.": "Le mauvais équipement peut sembler parfait sur papier.",
      "Specifications matter. So do application, operating conditions, support, lead time and commercial fit. MRLD starts there — then identifies the right equipment and source.": "Les spécifications comptent. L’application, les conditions d’exploitation, le soutien, les délais et l’adéquation commerciale aussi. MRLD commence par là — puis identifie l’équipement et la source qui conviennent.",
      "OUR SOURCING APPROACH": "NOTRE APPROCHE D’APPROVISIONNEMENT",
      "Your requirement sets the direction.": "Votre besoin dicte la marche à suivre.",
      "We start with the requirement, then find the source.": "Nous partons du besoin, puis nous trouvons la source.",
      "YOUR REQUIREMENT": "VOTRE BESOIN",
      "What must the equipment actually do?": "Que doit réellement accomplir l’équipement ?",
      "Application": "Application",
      "Specifications": "Spécifications",
      "Operating conditions": "Conditions d’exploitation",
      "Timeline": "Échéancier",
      "Support": "Soutien",
      "Commercial fit": "Adéquation commerciale",
      "Assess fit": "Évaluer l’adéquation",
      "Identify sources": "Identifier les sources",
      "Compare options": "Comparer les options",
      "Connect parties": "Mettre les parties en relation",
      "EQUIPMENT": "ÉQUIPEMENT",
      "A source that fits the requirement.": "Une source adaptée au besoin.",
      "Suitable equipment, a credible source, and a commercial path forward.": "Un équipement adapté, une source crédible et une voie commerciale claire pour aller de l’avant.",
      "When the requirement extends beyond the equipment, MRLD can also coordinate project logistics and delivery support.": "Lorsque le besoin dépasse l’équipement lui-même, MRLD peut aussi coordonner la logistique de projet et le soutien à la livraison.",
      "Explore Project Logistics →": "Explorer la logistique de projet →",
      "FOR MANUFACTURERS": "POUR LES FABRICANTS",
      "Want your equipment in the hands of new customers?": "Vous voulez mettre votre équipement entre les mains de nouveaux clients ?",
      "MRLD works with selected industrial equipment manufacturers seeking qualified buyer access and commercial development in new markets.": "MRLD travaille avec des fabricants sélectionnés d’équipement industriel qui cherchent à rejoindre des acheteurs qualifiés et à développer de nouveaux marchés.",
      "Discuss Your Equipment →": "Présentez-nous votre équipement →",
      "FOR BUYERS": "POUR LES ACHETEURS",
      "Have an equipment requirement?": "Vous avez un besoin en équipement ?",
      "Tell us what the equipment needs to do. We'll start there.": "Dites-nous ce que l’équipement doit accomplir. Nous commencerons par là.",
      "Discuss Your Requirement →": "Discuter de votre besoin →",
      "MRLD sourcing approach from requirement to equipment": "Approche d’approvisionnement de MRLD, du besoin à l’équipement"
    },
    "project-logistics": {
      "Project Logistics | MRLD": "Logistique de projet | MRLD",
      "MRLD coordinates industrial equipment projects from supplier to site, keeping parties, requirements, and delivery dependencies connected through specialized logistics providers.": "MRLD coordonne les projets d’équipement industriel du fournisseur jusqu’au site, en maintenant les parties, les exigences et les dépendances de livraison alignées avec l’appui de prestataires logistiques spécialisés.",
      "BEYOND THE ORDER": "AU-DELÀ DE LA COMMANDE",
      "The deal can be done. The project isn’t.": "L’entente peut être conclue. Le projet, lui, ne l’est pas.",
      "Between supplier and site, timelines, documentation, logistics partners, access and handoffs create risks. We keep the parties and requirements connected through delivery.": "Entre le fournisseur et le site, les échéanciers, la documentation, les partenaires logistiques, l’accès et les passages de relais créent des risques. Nous maintenons les parties et les exigences alignées jusqu’à la livraison.",
      "FROM SUPPLIER TO SITE": "DU FOURNISSEUR AU SITE",
      "Six points where coordination matters.": "Six points où la coordination compte.",
      "Each handoff introduces another dependency. Explore the path.": "Chaque passage de relais ajoute une dépendance. Parcourez le chemin.",
      "Supplier": "Fournisseur",
      "Planning": "Planification",
      "Partner Alignment": "Alignement des partenaires",
      "Cross-Border Movement": "Mouvement transfrontalier",
      "Site Readiness": "Préparation du site",
      "Delivery": "Livraison",
      "MRLD coordinates the path.": "MRLD coordonne le parcours.",
      "Specialized logistics providers execute transport and freight services.": "Les prestataires logistiques spécialisés prennent en charge les services de transport et de fret.",
      "HAVE A PROJECT IN MOTION?": "UN PROJET EST EN COURS ?",
      "Need equipment to reach the site?": "Votre équipement doit arriver sur le site ?",
      "Tell us what is moving, where it is coming from, where it needs to go, and what the project requires.": "Dites-nous ce qui doit être déplacé, d’où cela vient, où cela doit aller et ce que le projet exige.",
      "Discuss Your Delivery": "Discuter de votre livraison",
      "Six project logistics coordination points from supplier to site": "Six points de coordination logistique du fournisseur jusqu’au site",
      "Supplier — show details": "Fournisseur — afficher les détails",
      "Planning — show details": "Planification — afficher les détails",
      "Partner Alignment — show details": "Alignement des partenaires — afficher les détails",
      "Cross-Border Movement — show details": "Mouvement transfrontalier — afficher les détails",
      "Site Readiness — show details": "Préparation du site — afficher les détails",
      "Delivery — show details": "Livraison — afficher les détails",
      "Origin details, equipment readiness, dimensions and release timing establish the starting point.": "Les détails d’origine, l’état de préparation de l’équipement, ses dimensions et le moment de sa libération établissent le point de départ.",
      "Equipment dimensions, weight, route, timing and delivery constraints are established before movement begins.": "Les dimensions et le poids de l’équipement, l’itinéraire, l’échéancier et les contraintes de livraison sont établis avant le début du mouvement.",
      "Qualified logistics providers, suppliers, buyers and project stakeholders are aligned around responsibilities and timing.": "Les prestataires logistiques qualifiés, les fournisseurs, les acheteurs et les parties prenantes du projet sont alignés sur les responsabilités et l’échéancier.",
      "International movements require coordinated documentation, commercial communication and handoffs between specialized providers.": "Les mouvements internationaux exigent une coordination de la documentation, des communications commerciales et des passages de relais entre prestataires spécialisés.",
      "Access, scheduling, receiving requirements and site constraints are considered before arrival.": "L’accès, la planification, les exigences de réception et les contraintes du site sont pris en compte avant l’arrivée.",
      "The final handoff stays connected to the project plan so the equipment reaches its destination with the right parties ready.": "Le dernier passage de relais demeure lié au plan de projet afin que l’équipement arrive à destination avec les bonnes parties prêtes à intervenir."
    },
    "industries": {
      "Sectors | MRLD": "Secteurs | MRLD",
      "MRLD works across industrial environments including construction, mining, energy, manufacturing, infrastructure, and material handling.": "MRLD intervient dans des environnements industriels comprenant la construction, les mines, l’énergie, la fabrication, les infrastructures et la manutention.",
      "INDUSTRIAL ENVIRONMENTS": "ENVIRONNEMENTS INDUSTRIELS",
      "The machine fits the job or it doesn’t.": "La machine convient au travail — ou non.",
      "MRLD works across construction, mining, energy, manufacturing, infrastructure and material handling.": "MRLD intervient dans les secteurs de la construction, des mines, de l’énergie, de la fabrication, des infrastructures et de la manutention.",
      "YOUR INDUSTRY ISN’T THE LIMIT": "VOTRE SECTEUR N’EST PAS UNE LIMITE",
      "Have an equipment requirement?": "Vous avez un besoin en équipement ?",
      "Tell us what needs to be done.": "Dites-nous ce qui doit être accompli.",
      "Discuss Your Requirement": "Discuter de votre besoin",
      "Industrial sectors": "Secteurs industriels",
      "Excavator bucket detail on a construction site": "Détail du godet d’une excavatrice sur un chantier de construction",
      "Large mining machinery operating in a quarry": "Machinerie minière lourde en activité dans une carrière",
      "Heavy-duty diesel engine detail": "Détail d’un moteur diesel à usage intensif",
      "Industrial machinery and precision components in a factory": "Machinerie industrielle et composants de précision dans une usine",
      "Structural steel bridge framework": "Structure d’acier d’un pont",
      "Forklift operating inside an industrial warehouse": "Chariot élévateur en activité dans un entrepôt industriel"
    },
    "about": {
      "About MRLD | Built Between Markets": "À propos de MRLD | Née entre les marchés",
      "MRLD is a Canadian industrial equipment company with direct presence in Asia, connecting selected manufacturers with qualified buyers across markets.": "MRLD est une entreprise canadienne d’équipement industriel présente directement en Asie, qui met en relation des fabricants sélectionnés avec des acheteurs qualifiés sur différents marchés.",
      "CANADA → ASIA → BEYOND": "CANADA → ASIE → AU-DELÀ",
      "Built between markets.": "Née entre les marchés.",
      "MRLD combines a Canadian commercial base with direct presence in Asia, bringing market demand closer to industrial supply.": "MRLD conjugue une base commerciale canadienne à une présence directe en Asie, rapprochant la demande du marché de l’offre industrielle.",
      "Base": "Base",
      "Presence": "Présence",
      "Reach": "Portée",
      "FOUNDER & DIRECTOR": "FONDATEUR ET DIRECTEUR",
      "Technology · Business Development · Transformation": "Technologie · Développement des affaires · Transformation",
      "Ali’s background spans technology, international business development and organizational transformation, including roles with Apple and Holcim.": "Le parcours d’Ali couvre la technologie, le développement international des affaires et la transformation organisationnelle, notamment dans le cadre de fonctions chez Apple et Holcim.",
      "MRLD grew from a simple observation: capable manufacturers do not always have direct access to the markets where their equipment can create value, while buyers do not always have access to the suppliers best suited to their requirements.": "MRLD est née d’un constat simple : des fabricants compétents n’ont pas toujours un accès direct aux marchés où leur équipement peut créer de la valeur, tandis que les acheteurs n’ont pas toujours accès aux fournisseurs les mieux adaptés à leurs besoins.",
      "At MRLD, that experience takes a deliberately focused commercial form: developing relationships with selected manufacturers, identifying opportunities, and connecting equipment with qualified buyers.": "Chez MRLD, cette expérience prend une forme commerciale volontairement ciblée : développer des relations avec des fabricants sélectionnés, repérer des occasions et mettre leur équipement en relation avec des acheteurs qualifiés.",
      "The approach is practical: understand the requirement, identify the right people, and move the opportunity forward.": "L’approche est pratique : comprendre le besoin, identifier les bonnes personnes et faire avancer l’occasion.",
      "ONE OPERATING PRINCIPLE": "UN PRINCIPE DIRECTEUR",
      "Selective by design.": "Sélective par choix.",
      "MRLD works with manufacturers, buyers and opportunities where there is a credible commercial fit on both sides.": "MRLD travaille avec des fabricants, des acheteurs et des occasions lorsqu’il existe une adéquation commerciale crédible des deux côtés.",
      "Connect with Ali": "Communiquer avec Ali",
      "MRLD operates between Canada, Asia and international markets": "MRLD opère entre le Canada, l’Asie et les marchés internationaux",
      "Ali Saïd, Founder and Director of MRLD": "Ali Saïd, fondateur et directeur de MRLD"
    },
    "contact": {
      "Contact MRLD | Start a Conversation": "Contact MRLD | Engageons la conversation",
      "Contact MRLD about an industrial equipment requirement, manufacturer representation, project logistics, or another commercial opportunity.": "Communiquez avec MRLD au sujet d’un besoin en équipement industriel, de représentation de fabricant, de logistique de projet ou d’une autre occasion commerciale.",
      "START HERE": "COMMENCEZ ICI",
      "Bring us the requirement. Or the opportunity.": "Parlez-nous du besoin. Ou de l’occasion.",
      "Equipment sourcing, market representation or project logistics — tell us what you are trying to move forward.": "Approvisionnement en équipement, représentation commerciale ou logistique de projet — dites-nous ce que vous cherchez à faire avancer.",
      "START A CONVERSATION": "ENGAGEONS LA CONVERSATION",
      "Tell us what you’re working on.": "Parlez-nous de ce sur quoi vous travaillez.",
      "A few useful details are enough. We’ll take it from there.": "Quelques détails utiles suffisent. Nous prendrons le relais.",
      "Connect on LinkedIn": "Communiquer sur LinkedIn",
      "Name": "Nom",
      "Company": "Entreprise",
      "Phone": "Téléphone",
      "I’m interested in": "Je m’intéresse à",
      "Select an option": "Sélectionnez une option",
      "Equipment requirement": "Besoin en équipement",
      "Manufacturer representation": "Représentation de fabricants",
      "Project logistics": "Logistique de projet",
      "Other opportunity": "Autre occasion",
      "Industry / Sector": "Industrie / secteur",
      "Select a sector": "Sélectionnez un secteur",
      "Tell us more": "Dites-nous-en plus",
      "Send Inquiry": "Envoyer la demande",
      "Direct contact options": "Options de contact direct",
      "What are you trying to accomplish?": "Que cherchez-vous à accomplir ?"
    },
    "card": {
      "Ali Saïd — Founder & Director, MRLD. Industrial Equipment & Global Project Delivery.": "Ali Saïd — Fondateur et directeur, MRLD. Équipement industriel et exécution de projets internationaux.",
      "Industrial Equipment & Global Project Delivery": "Équipement industriel et exécution de projets internationaux",
      "A business of Sayudi Inc.": "Une entreprise de Sayudi Inc.",
      "Visit MRLD": "Visiter MRLD",
      "MRLD · Sayudi Inc. · Montreal, Canada": "MRLD · Sayudi Inc. · Montréal, Canada"
    },
    "connect": {
      "Connect | MRLD": "Nous joindre | MRLD",
      "Connect with Ali Saïd, Founder & Director of MRLD. Industrial Equipment & Global Project Delivery.": "Communiquez avec Ali Saïd, fondateur et directeur de MRLD. Équipement industriel et exécution de projets internationaux.",
      "Trade Show Connection": "Rencontre en salon professionnel",
      "Let's connect.": "Prenons contact.",
      "Start here": "Commencez ici",
      "What brings you to MRLD?": "Qu’est-ce qui vous amène chez MRLD ?",
      "Whether you're looking to enter a market, source equipment, or strengthen project delivery, there's a direct way to connect.": "Que vous cherchiez à entrer sur un marché, à trouver de l’équipement ou à renforcer l’exécution d’un projet, il existe une façon directe de nous joindre.",
      "Direct connection": "Contact direct",
      "Founder & Director · MRLD": "Fondateur et directeur · MRLD",
      "Connect with Ali Saïd on LinkedIn": "Communiquer avec Ali Saïd sur LinkedIn",
      "Call Ali": "Appeler Ali",
      "Email Ali": "Écrire à Ali",
      "I represent equipment": "Je représente une gamme d’équipement",
      "Manufacturer, supplier, or brand looking to reach new markets.": "Fabricant, fournisseur ou marque cherchant à rejoindre de nouveaux marchés.",
      "I need equipment": "J’ai besoin d’équipement",
      "Looking to source machinery, equipment, or a project solution.": "À la recherche de machinerie, d’équipement ou d’une solution pour un projet.",
      "I move equipment": "Je travaille en logistique",
      "Freight forwarder, carrier, customs, or specialized logistics partner.": "Transitaire, transporteur, spécialiste des douanes ou partenaire logistique spécialisé.",
      "Let's talk": "Parlons-en",
      "Something else in mind? Start a conversation with MRLD.": "Vous avez autre chose en tête ? Engagez la conversation avec MRLD.",
      "Visit the MRLD Website": "Visiter le site de MRLD",
      "Industrial Equipment · Project Delivery · Reliable Execution": "Équipement industriel · Exécution de projet · Fiabilité d’exécution",
      "A Sayudi Inc. company": "Une entreprise de Sayudi Inc."
    },
    "partner": {
      "MRLD | Partner Information": "MRLD | Renseignements pour les partenaires",
      "MRLD company and partnership information for prospective manufacturers, logistics providers, and project partners.": "Renseignements sur MRLD et ses partenariats à l’intention des fabricants, prestataires logistiques et partenaires de projet potentiels.",
      "PARTNER ACCESS": "ACCÈS PARTENAIRE",
      "MRLD company information.": "Renseignements sur MRLD.",
      "This page provides the company information required by prospective manufacturers, logistics providers, and project partners when moving forward with MRLD.": "Cette page présente les renseignements d’entreprise requis par les fabricants, prestataires logistiques et partenaires de projet potentiels lorsqu’ils souhaitent aller de l’avant avec MRLD.",
      "Access Code": "Code d’accès",
      "Continue": "Continuer",
      "Access code not recognized.": "Code d’accès non reconnu.",
      "If you received this page from an MRLD representative, use the access code provided with the invitation.": "Si un représentant de MRLD vous a transmis cette page, utilisez le code d’accès fourni avec l’invitation.",
      "MRLD · PARTNER INFORMATION": "MRLD · RENSEIGNEMENTS PARTENAIRES",
      "The information you need to work with us.": "Les renseignements nécessaires pour travailler avec nous.",
      "01 · COMPANY": "01 · ENTREPRISE",
      "Corporate information.": "Renseignements corporatifs.",
      "Standard company information for agreements, quotations, purchase documentation, and business correspondence.": "Renseignements standards de l’entreprise pour les ententes, soumissions, documents d’achat et correspondance d’affaires.",
      "Legal Company Name": "Dénomination sociale",
      "Doing Business As / Brand": "Nom commercial / marque",
      "Company Type": "Type d’entreprise",
      "Canadian Corporation": "Société canadienne",
      "Headquarters": "Siège social",
      "Montreal, Quebec, Canada": "Montréal, Québec, Canada",
      "Website": "Site Web",
      "Business Registration Number": "Numéro d’immatriculation de l’entreprise",
      "02 · CONTACT": "02 · CONTACT",
      "Primary contact.": "Contact principal.",
      "Direct contact information for commercial, partnership, and business development matters.": "Coordonnées directes pour les questions commerciales, les partenariats et le développement des affaires.",
      "Position": "Poste",
      "Direct Phone": "Téléphone direct",
      "LinkedIn Profile": "Profil LinkedIn",
      "03 · BUSINESS": "03 · ACTIVITÉS",
      "What MRLD does.": "Ce que fait MRLD.",
      "MRLD operates between selected industrial equipment manufacturers and qualified buyers, supporting the commercial path from market opportunity through delivery.": "MRLD agit entre des fabricants sélectionnés d’équipement industriel et des acheteurs qualifiés, en soutenant le parcours commercial depuis l’occasion de marché jusqu’à la livraison.",
      "Market Representation": "Représentation commerciale",
      "Represent selected manufacturers and develop commercial opportunities in target markets.": "Représenter des fabricants sélectionnés et développer des occasions commerciales dans les marchés ciblés.",
      "Equipment Sourcing": "Approvisionnement en équipement",
      "Identify suitable equipment and alternative supply sources for qualified buyers.": "Identifier de l’équipement adapté et des sources d’approvisionnement alternatives pour des acheteurs qualifiés.",
      "Project Delivery": "Exécution de projet",
      "Coordinate suppliers, logistics providers, documentation, and project requirements.": "Coordonner les fournisseurs, les prestataires logistiques, la documentation et les exigences du projet.",
      "04 · SCOPE": "04 · PORTÉE",
      "Markets & equipment.": "Marchés et équipement.",
      "MRLD is building a focused network rather than maintaining an open supplier directory.": "MRLD développe un réseau ciblé plutôt que de maintenir un répertoire ouvert de fournisseurs.",
      "Primary Market": "Marché principal",
      "Canada, with opportunities across international markets where appropriate.": "Le Canada, avec des occasions sur les marchés internationaux lorsque pertinent.",
      "Current Equipment Focus": "Catégories d’équipement actuelles",
      "Power generation, construction machinery, industrial equipment, and related infrastructure solutions.": "Production d’énergie, machinerie de construction, équipement industriel et solutions d’infrastructure connexes.",
      "05 · PARTNERSHIP": "05 · PARTENARIAT",
      "How we work.": "Notre façon de travailler.",
      "MRLD develops selective commercial relationships based on product fit, market opportunity, and the ability to execute.": "MRLD développe des relations commerciales sélectives selon l’adéquation du produit, l’occasion de marché et la capacité d’exécution.",
      "Manufacturer Representation": "Représentation de fabricants",
      "MRLD may represent selected manufacturers in defined markets and develop qualified commercial opportunities on their behalf.": "MRLD peut représenter des fabricants sélectionnés dans des marchés définis et développer en leur nom des occasions commerciales qualifiées.",
      "Project & Transaction Support": "Soutien aux projets et transactions",
      "Depending on the opportunity, MRLD may coordinate equipment sourcing, commercial discussions, logistics, documentation, and delivery.": "Selon l’occasion, MRLD peut coordonner l’approvisionnement en équipement, les discussions commerciales, la logistique, la documentation et la livraison.",
      "06 · AGREEMENT": "06 · ENTENTE",
      "Information required to move forward.": "Renseignements requis pour aller de l’avant.",
      "When preparing a partnership or representation agreement, the following information is typically required.": "Lors de la préparation d’une entente de partenariat ou de représentation, les renseignements suivants sont généralement requis.",
      "Full legal company name": "Dénomination sociale complète",
      "Registered company address": "Adresse officielle de l’entreprise",
      "Company registration information": "Renseignements d’immatriculation",
      "Authorized representative": "Représentant autorisé",
      "Representative's title and contact information": "Titre et coordonnées du représentant",
      "Commercial / partnership scope": "Portée commerciale / du partenariat",
      "Relevant product categories": "Catégories de produits pertinentes",
      "Payment and commission information, where applicable": "Renseignements sur le paiement et les commissions, le cas échéant",
      "07 · DOCUMENTS": "07 · DOCUMENTS",
      "Corporate documents.": "Documents corporatifs.",
      "Certain documents may be requested during formal onboarding or agreement preparation.": "Certains documents peuvent être demandés lors du processus officiel d’intégration ou de la préparation d’une entente.",
      "Corporate registration documents, tax information, banking information, and other supporting documentation are provided separately when required for a specific commercial relationship. This page is not intended to replace formal corporate documentation.": "Les documents d’immatriculation, renseignements fiscaux, renseignements bancaires et autres pièces justificatives sont fournis séparément lorsqu’une relation commerciale précise l’exige. Cette page ne remplace pas la documentation corporative officielle.",
      "NEXT STEP": "PROCHAINE ÉTAPE",
      "Ready to move forward?": "Passons à la prochaine étape.",
      "Send the required company information and MRLD can prepare the appropriate commercial documentation or next step.": "Transmettez les renseignements d’entreprise requis et MRLD pourra préparer la documentation commerciale appropriée ou la prochaine étape.",
      "Visit Contact Page": "Accéder à la page Contact",
      "Market Reach. Leverage. Development.": "Market Reach. Leverage. Development.",
      "Enter access code": "Entrez le code d’accès"
    },
    "privacy": {
      "Privacy Policy | MRLD": "Politique de confidentialité | MRLD",
      "Privacy Policy for MRLD, a Canadian industrial equipment and market access company.": "Politique de confidentialité de MRLD, une entreprise canadienne d’équipement industriel et d’accès aux marchés.",
      "PRIVACY": "CONFIDENTIALITÉ",
      "MRLD respects the privacy of individuals who interact with our website and is committed to handling personal information responsibly.": "MRLD respecte la vie privée des personnes qui interagissent avec notre site Web et s’engage à traiter les renseignements personnels de façon responsable.",
      "Our Privacy Practices": "Nos pratiques en matière de confidentialité",
      "This Privacy Policy explains how MRLD collects, uses, protects, and manages personal information submitted through this website.": "La présente politique de confidentialité explique comment MRLD recueille, utilise, protège et gère les renseignements personnels transmis par l’entremise de ce site Web.",
      "01. Who We Are": "01. Qui nous sommes",
      "MRLD is a Canadian company and a business of Sayudi Inc. MRLD operates in the industrial equipment and commercial representation sector, connecting selected manufacturers, suppliers, buyers, and project partners across markets.": "MRLD est une entreprise canadienne faisant partie de Sayudi Inc. Elle œuvre dans le secteur de l’équipement industriel et de la représentation commerciale, en mettant en relation des fabricants, fournisseurs, acheteurs et partenaires de projet sélectionnés sur différents marchés.",
      "For questions concerning privacy or the handling of personal information, you may contact us using the information below.": "Pour toute question concernant la confidentialité ou le traitement des renseignements personnels, vous pouvez communiquer avec nous aux coordonnées ci-dessous.",
      "02. Information We Collect": "02. Renseignements que nous recueillons",
      "MRLD may collect personal information that you voluntarily provide when you contact us or submit an inquiry through this website.": "MRLD peut recueillir les renseignements personnels que vous fournissez volontairement lorsque vous communiquez avec nous ou soumettez une demande par l’entremise de ce site Web.",
      "Depending on the nature of your inquiry, this may include:": "Selon la nature de votre demande, ces renseignements peuvent comprendre :",
      "Your name": "Votre nom",
      "Company or organization name": "Le nom de votre entreprise ou organisation",
      "Email address": "Votre adresse courriel",
      "Telephone number": "Votre numéro de téléphone",
      "Industry and project information": "Des renseignements sur votre secteur et votre projet",
      "Equipment or logistics requirements": "Vos besoins en équipement ou en logistique",
      "Other information you choose to provide in your message": "Tout autre renseignement que vous choisissez de fournir dans votre message",
      "We seek to collect only information that is reasonably necessary for the purpose for which it is requested.": "Nous cherchons à recueillir uniquement les renseignements raisonnablement nécessaires aux fins pour lesquelles ils sont demandés.",
      "03. How We Use Personal Information": "03. Utilisation des renseignements personnels",
      "Personal information submitted to MRLD may be used to:": "Les renseignements personnels transmis à MRLD peuvent être utilisés pour :",
      "Respond to inquiries and requests": "Répondre aux demandes et aux requêtes",
      "Understand equipment, sourcing, or project requirements": "Comprendre les besoins en équipement, en approvisionnement ou liés à un projet",
      "Evaluate potential business opportunities": "Évaluer des occasions d’affaires potentielles",
      "Communicate with prospective clients, manufacturers, suppliers, and partners": "Communiquer avec des clients, fabricants, fournisseurs et partenaires potentiels",
      "Coordinate services or project-related activities": "Coordonner des services ou des activités liées à un projet",
      "Maintain business records and communications": "Conserver les dossiers et communications d’affaires",
      "Meet applicable legal or regulatory obligations": "Respecter les obligations légales ou réglementaires applicables",
      "MRLD does not use personal information for purposes unrelated to the purpose for which it was collected unless permitted or required by law.": "MRLD n’utilise pas les renseignements personnels à des fins étrangères à celles pour lesquelles ils ont été recueillis, sauf lorsque la loi le permet ou l’exige.",
      "04. Disclosure of Personal Information": "04. Communication des renseignements personnels",
      "MRLD does not sell or rent personal information.": "MRLD ne vend ni ne loue les renseignements personnels.",
      "Where reasonably necessary to respond to an inquiry or support a project, information may be shared with service providers, suppliers, logistics providers, manufacturers, professional advisers, or other parties involved in the relevant business activity.": "Lorsque cela est raisonnablement nécessaire pour répondre à une demande ou soutenir un projet, des renseignements peuvent être communiqués à des fournisseurs de services, fournisseurs, prestataires logistiques, fabricants, conseillers professionnels ou autres parties participant à l’activité commerciale concernée.",
      "Information may also be disclosed where required or permitted by applicable law.": "Des renseignements peuvent également être communiqués lorsque les lois applicables l’exigent ou le permettent.",
      "Some service providers used to operate this website or process communications may store or process information outside Canada or outside the jurisdiction in which you reside.": "Certains fournisseurs de services utilisés pour exploiter ce site Web ou traiter les communications peuvent stocker ou traiter des renseignements à l’extérieur du Canada ou de la juridiction où vous résidez.",
      "05. Website Forms and Service Providers": "05. Formulaires du site Web et fournisseurs de services",
      "MRLD uses third-party service providers to operate certain website functions, including the processing and delivery of contact form submissions.": "MRLD fait appel à des fournisseurs de services tiers pour exploiter certaines fonctions du site Web, notamment le traitement et l’acheminement des formulaires de contact.",
      "Information submitted through an MRLD contact form may therefore be transmitted to the third-party service provider responsible for processing that submission.": "Les renseignements transmis par un formulaire de contact de MRLD peuvent donc être acheminés au fournisseur de services tiers responsable du traitement de cette soumission.",
      "These providers may process or store information in jurisdictions outside Canada. Their handling of information is governed by their respective privacy policies and terms.": "Ces fournisseurs peuvent traiter ou stocker des renseignements dans des juridictions situées à l’extérieur du Canada. Leur traitement des renseignements est régi par leurs politiques de confidentialité et leurs conditions respectives.",
      "06. Cookies and Website Technologies": "06. Témoins et technologies du site Web",
      "MRLD may use basic technologies that are necessary for the operation, security, and functionality of this website.": "MRLD peut utiliser des technologies de base nécessaires au fonctionnement, à la sécurité et aux fonctionnalités de ce site Web.",
      "At this time, MRLD does not intentionally use this website to collect sensitive personal information through tracking technologies.": "À l’heure actuelle, MRLD n’utilise pas intentionnellement ce site Web pour recueillir des renseignements personnels sensibles au moyen de technologies de suivi.",
      "If additional analytics, advertising, or tracking technologies are introduced, this Privacy Policy may be updated to reflect those practices.": "Si des technologies supplémentaires d’analyse, de publicité ou de suivi sont introduites, la présente politique de confidentialité pourra être mise à jour afin de refléter ces pratiques.",
      "07. Protection of Personal Information": "07. Protection des renseignements personnels",
      "MRLD takes reasonable administrative, technical, and organizational measures to protect personal information against unauthorized access, use, disclosure, loss, or destruction.": "MRLD prend des mesures administratives, techniques et organisationnelles raisonnables afin de protéger les renseignements personnels contre l’accès, l’utilisation ou la communication non autorisés, ainsi que contre la perte ou la destruction.",
      "However, no method of transmission or storage over the Internet can be guaranteed to be completely secure.": "Toutefois, aucune méthode de transmission ou de stockage sur Internet ne peut être garantie comme étant entièrement sécuritaire.",
      "08. Retention of Personal Information": "08. Conservation des renseignements personnels",
      "MRLD retains personal information only for as long as reasonably necessary to fulfil the purposes for which it was collected, to maintain appropriate business records, or to meet legal or regulatory requirements.": "MRLD conserve les renseignements personnels uniquement pendant la durée raisonnablement nécessaire pour atteindre les fins pour lesquelles ils ont été recueillis, tenir des dossiers d’affaires appropriés ou respecter les exigences légales ou réglementaires.",
      "When personal information is no longer required, it may be securely deleted, destroyed, or otherwise disposed of in accordance with applicable requirements.": "Lorsque les renseignements personnels ne sont plus requis, ils peuvent être supprimés, détruits ou autrement éliminés de façon sécuritaire conformément aux exigences applicables.",
      "09. Access and Correction": "09. Accès et rectification",
      "Subject to applicable law, individuals may request access to personal information held by MRLD about them and may request correction of information that is inaccurate or incomplete.": "Sous réserve des lois applicables, toute personne peut demander l’accès aux renseignements personnels que MRLD détient à son sujet et demander la rectification de renseignements inexacts ou incomplets.",
      "Requests concerning personal information should be directed to the contact identified below.": "Les demandes concernant les renseignements personnels doivent être adressées au contact indiqué ci-dessous.",
      "10. Consent": "10. Consentement",
      "By voluntarily providing personal information through this website, you acknowledge that MRLD may collect, use, and disclose that information for the purposes described in this Privacy Policy, subject to applicable law.": "En fournissant volontairement des renseignements personnels par l’entremise de ce site Web, vous reconnaissez que MRLD peut recueillir, utiliser et communiquer ces renseignements aux fins décrites dans la présente politique de confidentialité, sous réserve des lois applicables.",
      "Where consent is required, individuals may have the right to withdraw their consent, subject to legal or contractual restrictions and reasonable notice.": "Lorsque le consentement est requis, les personnes peuvent avoir le droit de le retirer, sous réserve de restrictions légales ou contractuelles et d’un préavis raisonnable.",
      "11. Privacy Inquiries": "11. Demandes relatives à la confidentialité",
      "Questions, requests, or concerns regarding the handling of personal information may be directed to:": "Les questions, demandes ou préoccupations concernant le traitement des renseignements personnels peuvent être adressées à :",
      "Email:": "Courriel :",
      "MRLD will review privacy inquiries and respond within a reasonable period, subject to applicable requirements.": "MRLD examinera les demandes relatives à la confidentialité et y répondra dans un délai raisonnable, sous réserve des exigences applicables.",
      "12. Updates to This Policy": "12. Modifications à la présente politique",
      "MRLD may update this Privacy Policy from time to time to reflect changes to its practices, services, technology, or applicable legal requirements.": "MRLD peut mettre à jour la présente politique de confidentialité à l’occasion afin de refléter des changements à ses pratiques, à ses services, à sa technologie ou aux exigences légales applicables.",
      "The most recent version will be published on this page.": "La version la plus récente sera publiée sur cette page.",
      "Have a Privacy Question?": "Une question sur la confidentialité ?",
      "Contact MRLD if you have a question about how your information is collected or handled.": "Communiquez avec MRLD si vous avez une question sur la façon dont vos renseignements sont recueillis ou traités."
    },
    "terms": {
      "Terms of Use | MRLD": "Conditions d’utilisation | MRLD",
      "Terms of Use for the MRLD website.": "Conditions d’utilisation du site Web de MRLD.",
      "LEGAL": "MENTIONS LÉGALES",
      "These terms govern your use of the MRLD website and its publicly available content.": "Les présentes conditions régissent votre utilisation du site Web de MRLD et de son contenu accessible au public.",
      "Use of This Website": "Utilisation de ce site Web",
      "Please read these Terms of Use before using the MRLD website. By accessing or using this website, you acknowledge that you have read and understood these terms.": "Veuillez lire les présentes conditions d’utilisation avant d’utiliser le site Web de MRLD. En accédant à ce site Web ou en l’utilisant, vous reconnaissez avoir lu et compris ces conditions.",
      "01. About MRLD": "01. À propos de MRLD",
      "MRLD is a Canadian business operating as part of Sayudi Inc. MRLD connects selected industrial equipment manufacturers, suppliers, buyers, and project partners across Canada and international markets.": "MRLD est une entreprise canadienne exploitée au sein de Sayudi Inc. MRLD met en relation des fabricants sélectionnés d’équipement industriel, des fournisseurs, des acheteurs et des partenaires de projet au Canada et sur les marchés internationaux.",
      "Information presented on this website is provided for general informational and commercial purposes. Accessing this website does not by itself establish a client, agency, distribution, representation, partnership, or other contractual relationship between you and MRLD.": "Les renseignements présentés sur ce site Web sont fournis à des fins générales d’information et d’affaires. Le simple fait d’accéder à ce site Web n’établit aucune relation de client, d’agence, de distribution, de représentation, de partenariat ni aucune autre relation contractuelle entre vous et MRLD.",
      "02. Website Content": "02. Contenu du site Web",
      "MRLD makes reasonable efforts to ensure that information presented on this website is accurate and useful. However, equipment availability, specifications, pricing, supplier relationships, market conditions, delivery requirements, and other commercial information may change without notice.": "MRLD déploie des efforts raisonnables pour s’assurer que les renseignements présentés sur ce site Web sont exacts et utiles. Toutefois, la disponibilité de l’équipement, les spécifications, les prix, les relations avec les fournisseurs, les conditions de marché, les exigences de livraison et d’autres renseignements commerciaux peuvent changer sans préavis.",
      "Website content should therefore not be treated as a definitive quotation, technical specification, offer, warranty, or commitment to supply.": "Le contenu du site Web ne doit donc pas être considéré comme une soumission définitive, une spécification technique, une offre, une garantie ou un engagement d’approvisionnement.",
      "Specific equipment, sourcing, representation, logistics, or project arrangements are subject to separate discussions, verification, and where applicable, written agreements.": "Les arrangements précis relatifs à l’équipement, à l’approvisionnement, à la représentation, à la logistique ou à un projet font l’objet de discussions distinctes, de vérifications et, le cas échéant, d’ententes écrites.",
      "03. Equipment and Supplier Information": "03. Renseignements sur l’équipement et les fournisseurs",
      "MRLD may present information about equipment categories, manufacturers, suppliers, applications, or market opportunities.": "MRLD peut présenter des renseignements sur des catégories d’équipement, des fabricants, des fournisseurs, des applications ou des occasions de marché.",
      "The appearance of a manufacturer, supplier, equipment category, or other commercial reference on this website does not necessarily indicate an exclusive relationship, endorsement, authorization, availability, or current commercial agreement.": "La présence d’un fabricant, d’un fournisseur, d’une catégorie d’équipement ou de toute autre référence commerciale sur ce site Web n’indique pas nécessairement une relation exclusive, une approbation, une autorisation, une disponibilité ou une entente commerciale en vigueur.",
      "Equipment specifications, certifications, availability, condition, pricing, delivery timelines, and suitability must be independently confirmed as part of any specific transaction or project.": "Les spécifications, certifications, disponibilités, états, prix, délais de livraison et l’adéquation de l’équipement doivent être confirmés de façon indépendante dans le cadre de toute transaction ou de tout projet précis.",
      "04. Inquiries and Communications": "04. Demandes et communications",
      "Information submitted through the MRLD contact form or other communication channels may be reviewed to determine whether MRLD can assist with a sourcing, representation, logistics, or other commercial requirement.": "Les renseignements transmis au moyen du formulaire de contact de MRLD ou d’autres canaux de communication peuvent être examinés afin de déterminer si MRLD peut répondre à un besoin d’approvisionnement, de représentation, de logistique ou à un autre besoin commercial.",
      "Submission of an inquiry does not guarantee that MRLD will accept, pursue, or provide services relating to the inquiry.": "La soumission d’une demande ne garantit pas que MRLD acceptera, poursuivra ou fournira des services relativement à cette demande.",
      "Any commercial engagement, representation arrangement, sourcing mandate, logistics service, commission arrangement, or other business relationship will be governed by the terms agreed between the relevant parties.": "Tout engagement commercial, arrangement de représentation, mandat d’approvisionnement, service logistique, arrangement de commission ou autre relation d’affaires sera régi par les conditions convenues entre les parties concernées.",
      "05. No Professional or Technical Advice": "05. Aucun conseil professionnel ou technique",
      "Content published on this website is not intended to replace professional engineering, legal, financial, technical, regulatory, customs, transportation, or other specialized advice.": "Le contenu publié sur ce site Web ne vise pas à remplacer des conseils professionnels en ingénierie, en droit, en finances, en technique, en réglementation, en douanes, en transport ou dans tout autre domaine spécialisé.",
      "Users are responsible for obtaining appropriate professional advice and conducting their own due diligence before making equipment, procurement, investment, logistics, or operational decisions.": "Les utilisateurs sont responsables d’obtenir les conseils professionnels appropriés et d’effectuer leur propre diligence raisonnable avant de prendre des décisions concernant l’équipement, l’approvisionnement, l’investissement, la logistique ou les opérations.",
      "06. Third-Party Services and Links": "06. Services et liens de tiers",
      "This website may contain links to third-party websites, platforms, manufacturers, suppliers, service providers, or other external resources.": "Ce site Web peut contenir des liens vers des sites Web, plateformes, fabricants, fournisseurs, fournisseurs de services ou autres ressources externes de tiers.",
      "These links are provided for convenience and informational purposes. MRLD does not control and is not responsible for the content, availability, security, privacy practices, or terms of third-party websites or services.": "Ces liens sont fournis à titre pratique et informatif. MRLD ne contrôle pas et n’est pas responsable du contenu, de la disponibilité, de la sécurité, des pratiques de confidentialité ou des conditions des sites Web ou services de tiers.",
      "Your use of third-party websites and services is subject to their respective terms and policies.": "Votre utilisation de sites Web et de services de tiers est assujettie à leurs conditions et politiques respectives.",
      "07. Intellectual Property": "07. Propriété intellectuelle",
      "Unless otherwise indicated, the content of this website, including text, branding, logos, graphics, design elements, layouts, and other materials, is owned by or licensed to MRLD or Sayudi Inc. and is protected by applicable intellectual property laws.": "Sauf indication contraire, le contenu de ce site Web, y compris les textes, éléments de marque, logos, graphiques, éléments de conception, mises en page et autres contenus, appartient à MRLD ou à Sayudi Inc., ou leur est concédé sous licence, et est protégé par les lois applicables en matière de propriété intellectuelle.",
      "You may view and use the website for lawful personal or business purposes. You may not reproduce, distribute, modify, publish, transmit, sell, or commercially exploit website content without prior written permission, except where permitted by law.": "Vous pouvez consulter et utiliser le site Web à des fins personnelles ou commerciales légitimes. Vous ne pouvez pas reproduire, distribuer, modifier, publier, transmettre, vendre ou exploiter commercialement le contenu du site Web sans autorisation écrite préalable, sauf lorsque la loi le permet.",
      "08. Acceptable Use": "08. Utilisation acceptable",
      "You agree to use this website only for lawful purposes and in a manner that does not interfere with its operation or the rights of MRLD or others.": "Vous acceptez d’utiliser ce site Web uniquement à des fins légitimes et d’une manière qui ne nuit pas à son fonctionnement ni aux droits de MRLD ou d’autrui.",
      "You must not attempt to gain unauthorized access to the website, its systems, accounts, data, or infrastructure; use the website to distribute malicious code; or engage in activities intended to disrupt or compromise its operation.": "Vous ne devez pas tenter d’obtenir un accès non autorisé au site Web, à ses systèmes, comptes, données ou infrastructures; utiliser le site Web pour diffuser du code malveillant; ni entreprendre des activités visant à perturber ou à compromettre son fonctionnement.",
      "09. Website Availability": "09. Disponibilité du site Web",
      "MRLD does not guarantee that this website will always be available, uninterrupted, secure, or free from errors.": "MRLD ne garantit pas que ce site Web sera toujours disponible, ininterrompu, sécuritaire ou exempt d’erreurs.",
      "MRLD may modify, suspend, discontinue, or restrict access to any portion of the website at any time without notice.": "MRLD peut modifier, suspendre, interrompre ou restreindre l’accès à toute partie du site Web en tout temps, sans préavis.",
      "10. Limitation of Liability": "10. Limitation de responsabilité",
      "To the extent permitted by applicable law, MRLD and Sayudi Inc. shall not be liable for losses or damages arising from reliance on information presented on this website, inability to access the website, interruptions or technical failures, third-party websites or services, or decisions made based on website content.": "Dans la mesure permise par les lois applicables, MRLD et Sayudi Inc. ne pourront être tenues responsables de pertes ou dommages découlant de la confiance accordée aux renseignements présentés sur ce site Web, de l’impossibilité d’y accéder, d’interruptions ou de défaillances techniques, de sites Web ou services de tiers, ou de décisions prises sur la foi du contenu du site Web.",
      "Nothing in these Terms of Use excludes or limits liability where such exclusion or limitation is prohibited by applicable law.": "Aucune disposition des présentes conditions d’utilisation n’exclut ni ne limite une responsabilité lorsque cette exclusion ou limitation est interdite par les lois applicables.",
      "11. Indemnification": "11. Indemnisation",
      "To the extent permitted by applicable law, you agree to indemnify and hold harmless MRLD and Sayudi Inc., and their respective directors, officers, employees, and representatives, from claims, losses, liabilities, or expenses arising from your unlawful use of the website or violation of these Terms of Use.": "Dans la mesure permise par les lois applicables, vous acceptez d’indemniser et de tenir indemnes MRLD et Sayudi Inc., ainsi que leurs administrateurs, dirigeants, employés et représentants respectifs, à l’égard de toute réclamation, perte, responsabilité ou dépense découlant de votre utilisation illégale du site Web ou de votre violation des présentes conditions d’utilisation.",
      "12. Privacy": "12. Confidentialité",
      "Your use of this website is also subject to the": "Votre utilisation de ce site Web est également assujettie à la",
      ", which explains how personal information submitted through the website may be collected, used, disclosed, and protected.": ", qui explique comment les renseignements personnels transmis par l’entremise du site Web peuvent être recueillis, utilisés, communiqués et protégés.",
      "13. Governing Law": "13. Droit applicable",
      "These Terms of Use are governed by the laws applicable in the Canadian jurisdiction in which Sayudi Inc. is legally established, without regard to conflict-of-law principles.": "Les présentes conditions d’utilisation sont régies par les lois applicables dans la juridiction canadienne où Sayudi Inc. est légalement constituée, sans égard aux principes de conflit de lois.",
      "Any dispute relating to these Terms of Use shall be subject to the jurisdiction of the applicable courts of that jurisdiction, unless otherwise required by law.": "Tout différend relatif aux présentes conditions d’utilisation sera soumis à la compétence des tribunaux applicables de cette juridiction, sauf exigence contraire de la loi.",
      "14. Changes to These Terms": "14. Modifications aux présentes conditions",
      "MRLD may update these Terms of Use from time to time to reflect changes to the website, business practices, services, or applicable legal requirements.": "MRLD peut mettre à jour les présentes conditions d’utilisation à l’occasion afin de refléter des changements au site Web, aux pratiques d’affaires, aux services ou aux exigences légales applicables.",
      "Have a Question About MRLD?": "Une question au sujet de MRLD ?",
      "If you have questions about our services, equipment sourcing, market representation, or these Terms of Use, contact us directly.": "Si vous avez des questions sur nos services, l’approvisionnement en équipement, la représentation commerciale ou les présentes conditions d’utilisation, communiquez directement avec nous."
    },
    "bridge": {
      "INDUSTRIAL EQUIPMENT · GLOBAL SUPPLY": "ÉQUIPEMENT INDUSTRIEL · APPROVISIONNEMENT MONDIAL",
      "Connecting manufacturers with buyers.": "Relier les fabricants aux acheteurs.",
      "THE MRLD BRIDGE": "LE PONT MRLD",
      "Supply": "Offre",
      "Global": "Mondial",
      "Market Access": "Accès aux marchés",
      "Demand": "Demande",
      "Qualified": "Qualifiés",
      "Representation": "Représentation",
      "Sourcing": "Approvisionnement",
      "Delivery": "Livraison",
      "One connection between global supply and qualified demand.": "Un seul lien entre l’offre mondiale et une demande qualifiée.",
      "MRLD works on both sides of the industrial equipment market: helping selected manufacturers reach new buyers while helping organizations identify reliable equipment and alternative sources beyond their traditional supplier networks.": "MRLD intervient des deux côtés du marché de l’équipement industriel : aider des fabricants sélectionnés à rejoindre de nouveaux acheteurs, tout en aidant les organisations à repérer de l’équipement fiable et des sources alternatives au-delà de leurs réseaux de fournisseurs habituels.",
      "Looking to grow into new markets?": "Vous cherchez à développer de nouveaux marchés ?",
      "MRLD provides market representation, business development, and access to qualified buyers for selected equipment manufacturers seeking opportunities in Canada and beyond.": "MRLD offre de la représentation commerciale, du développement des affaires et un accès à des acheteurs qualifiés pour des fabricants d’équipement sélectionnés qui cherchent des occasions au Canada et au-delà.",
      "Looking for another source?": "Vous cherchez une autre source d’approvisionnement ?",
      "MRLD helps organizations identify and source industrial equipment from selected international manufacturers through a Canadian commercial point of contact.": "MRLD aide les organisations à repérer et à se procurer de l’équipement industriel auprès de fabricants internationaux sélectionnés, par l’entremise d’un point de contact commercial canadien.",
      "SELECTED EQUIPMENT": "ÉQUIPEMENT SÉLECTIONNÉ",
      "Industrial equipment for demanding operational environments.": "De l’équipement industriel pour des environnements d’exploitation exigeants.",
      "MRLD is building a focused network of equipment manufacturers across categories where supplier access, reliability, and execution matter.": "MRLD développe un réseau ciblé de fabricants d’équipement dans des catégories où l’accès aux fournisseurs, la fiabilité et la capacité d’exécution comptent.",
      "Diesel generators and power generation equipment.": "Génératrices diesel et équipement de production d’énergie.",
      "Equipment for construction, infrastructure, and earthmoving.": "Équipement pour la construction, les infrastructures et les travaux de terrassement.",
      "More Equipment Categories — Coming Soon": "Autres catégories d’équipement — à venir",
      "MRLD is actively expanding its manufacturer network.": "MRLD développe activement son réseau de fabricants.",
      "MARKET ACCESS": "ACCÈS AUX MARCHÉS",
      "More than a supplier directory.": "Plus qu’un répertoire de fournisseurs.",
      "MRLD selectively develops manufacturer relationships and connects them with real market opportunities. We support the commercial path from initial requirement and supplier identification through coordination and delivery.": "MRLD développe de façon sélective des relations avec des fabricants et les relie à de réelles occasions de marché. Nous soutenons le parcours commercial, du besoin initial et de l’identification du fournisseur jusqu’à la coordination et la livraison.",
      "Identify": "Identifier",
      "Understand equipment requirements, market opportunities, specifications, and project conditions.": "Comprendre les besoins en équipement, les occasions de marché, les spécifications et les conditions du projet.",
      "Connect": "Relier",
      "Match qualified buyers, manufacturers, equipment, and commercial opportunities.": "Faire correspondre acheteurs qualifiés, fabricants, équipement et occasions commerciales.",
      "Coordinate": "Coordonner",
      "Align suppliers, logistics providers, stakeholders, documentation, and project requirements.": "Aligner les fournisseurs, prestataires logistiques, parties prenantes, documents et exigences du projet.",
      "Deliver": "Livrer",
      "Support the movement from commercial opportunity through equipment delivery and project execution.": "Soutenir le passage de l’occasion commerciale à la livraison de l’équipement et à l’exécution du projet."
    }
  },
  "preserve": [
    "MRLD",
    "Sayudi Inc.",
    "Ali Saïd",
    "LinkedIn",
    "contact@sayudi.com",
    "ali@sayudi.com",
    "+1 (438) 969-9697",
    "mrldx.com",
    "1178738887",
    "MRLD2026",
    "TEL",
    "WEB",
    "IN",
    "MFR",
    "BUY",
    "LOG",
    "MARKET REACH · LEVERAGE · DEVELOPMENT",
    "Market Reach. Leverage. Development.",
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "→",
    "↗",
    "↔︎",
    "✓",
    "/",
    "@"
  ]
};
