#!/usr/bin/env python3
"""Extract the canonical English source strings used by the MRLD i18n layer.

The HTML remains the source of truth. This catalog is generated for review and
for preparing new locale files; do not edit the catalog by hand.
"""
from __future__ import annotations
import json, re
from pathlib import Path
from bs4 import BeautifulSoup, Comment

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content" / "en-catalog.json"
ATTRS = ["aria-label", "placeholder", "alt", "title", "data-title", "data-detail"]

def norm(value: str) -> str:
    return re.sub(r"\s+", " ", value or "").strip()

def page_name(path: Path) -> str:
    return "home" if path.stem == "index" else path.stem

pages = {}
for path in sorted(p for p in ROOT.rglob("*.html") if "__MACOSX" not in p.parts):
    soup = BeautifulSoup(path.read_text(encoding="utf-8"), "html.parser")
    for tag in soup(["style", "script", "noscript", "code", "pre"]):
        tag.decompose()

    strings = []
    if soup.title:
        strings.append(norm(soup.title.get_text(" ", strip=True)))
    desc = soup.find("meta", attrs={"name": "description"})
    if desc and desc.get("content"):
        strings.append(norm(desc["content"]))

    if soup.body:
        for node in soup.body.find_all(string=True):
            if isinstance(node, Comment):
                continue
            value = norm(str(node))
            if value:
                strings.append(value)
        for element in soup.body.find_all(True):
            for attr in ATTRS:
                value = norm(element.get(attr, ""))
                if value:
                    strings.append(value)

    deduped = list(dict.fromkeys(strings))
    pages[page_name(path)] = {
        "source_file": str(path.relative_to(ROOT)),
        "strings": deduped,
    }

catalog = {
    "meta": {
        "locale": "en",
        "source_of_truth": "HTML files in repository root and /pages",
        "generated_by": "tools/i18n-extract.py",
        "note": "Regenerate after changing canonical English copy. Do not edit this file manually."
    },
    "pages": pages,
}
OUT.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {OUT.relative_to(ROOT)} with {sum(len(v['strings']) for v in pages.values())} page-string entries.")
